[package]
name = "vulkan-loader-sys"
version = "1.3.235"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
cmake = "0.1.49"
bindgen = "0.63.0"
